/* Proyecto 2

Bases de datos de VenTruePe Muebles

En este archivo se colocan las restricciones a las tablas ya creadas.

Integrantes:
- Edgar Silva, carnet: 11-10968
- Douglas Torres, carnet: 11-11027
*/

-- Restricciones de claves primarias

ALTER TABLE EMPLEADO
	ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (CI_EMP);

ALTER TABLE DEPENDIENTES
	ADD CONSTRAINT PK_DEPENDIENTES PRIMARY KEY (POSTIZA_DEP);

ALTER TABLE PRIMA
	ADD CONSTRAINT PK_PRIMA PRIMARY KEY (POSTIZA_PRIMA);

ALTER TABLE CARGO
	ADD CONSTRAINT PK_CARGO PRIMARY KEY (POSTIZA_CARGO);

ALTER TABLE CATEGORIA
	ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (POSTIZA_CATEGORIA);

ALTER TABLE PRODUCTOS
	ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY (POSTIZA_PROD);

ALTER TABLE INVENTARIO_N
	ADD CONSTRAINT PK_INVENTARIO_N PRIMARY KEY (NUMERO_INV_N);

ALTER TABLE INVENTARIO_U
	ADD CONSTRAINT PK_INVENTARIO_U PRIMARY KEY (NUMERO_INV_U);

ALTER TABLE ORDEN
	ADD CONSTRAINT PK_ORDEN PRIMARY KEY (NRO_ORDEN);

ALTER TABLE PROVEEDORA
	ADD CONSTRAINT PK_PROVEEDORA PRIMARY KEY (RIF);

ALTER TABLE FACTURA
	ADD CONSTRAINT PK_FACTURA PRIMARY KEY (NUMERO_FACTURA);

ALTER TABLE TRANSFERENCIA
	ADD CONSTRAINT PK_TRANSFERENCIA PRIMARY KEY (NUMERO_TRANSACCION);

ALTER TABLE CLIENTE
	ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (CI_CL);

ALTER TABLE OPERACIONES
	ADD CONSTRAINT PK_OPERACIONES PRIMARY KEY (POSTIZA_OPERACIONES);

ALTER TABLE PAGOS
	ADD CONSTRAINT PK_PAGOS PRIMARY KEY (POSTIZA_PAGOS);

ALTER TABLE COMPRA
	ADD CONSTRAINT PK_COMPRA PRIMARY KEY (FACTURA_COMPRA);

-- Restricciones de claves foraneas

ALTER TABLE TELEFONO_DE_EMPLEADO 
	ADD CONSTRAINT FK_EMPLEADO_TELEFONO_DE_EMPLEADO FOREIGN KEY (CI_EMP);

ALTER TABLE PAGA
	ADD CONSTRAINT FK_EMPLEADO_PAGA FOREIGN KEY (CI_EMP);
	ADD CONSTRAINT FK_PRIMA_PAGA FOREIGN KEY (POSTIZA_PRIMA);
	ADD CONSTRAINT FK_DEPENDIENTES_PAGA FOREIGN KEY (POSTIZA_DEP);

ALTER TABLE ADMINISTRATIVO
	ADD CONSTRAINT FK_EMPLEADO_ADMINISTRATIVO FOREIGN KEY (CI_EMP);

ALTER TABLE VENDEDORES
	ADD CONSTRAINT FK_EMPLEADO_VENDEDORES FOREIGN KEY (CI_EMP);

ALTER TABLE VENDE
	ADD CONSTRAINT FK_EMPLEADO_VENDE FOREIGN KEY (CI_EMP);
	ADD CONSTRAINT FK_PRODUCTOS_VENDE FOREIGN KEY (POSTIZA_PROD);