/* Proyecto 2

Bases de datos de VenTruePe Muebles

En este archivo se crean todas las tablas con sus atributos correspondientes.
Las restricciones vendran dadas en otro archivo.

Integrantes:
- Edgar Silva, carnet: 11-10968
- Douglas Torres, carnet: 11-11027
*/

CREATE TABLE EMPLEADO (
	NOMBRE_EMP VARCHAR(20) NOT NULL, 
	APELLIDO_EMP VARCHAR(20) NOT NULL,
	CI_EMP VARCHAR(9) NOT NULL,
	DIRECCION_EMP VARCHAR(100) NOT NULL,
	CORREO_EMP VARCHAR(40) NOT NULL,
	FECHA_INGRESO_EMP TIMESTAMP NOT NULL
);

CREATE TABLE TELEFONO_DE_EMPLEADO (
	CI_EMP VARCHAR(9) NOT NULL,
	TELEFONO_EMP NUMERIC(11,0) NOT NULL

);

CREATE TABLE DEPENDIENTES (
	POSTIZA_DEP INT NOT NULL,
	NOMBRE_DEP VARCHAR(20) NOT NULL,
	APELLIDO_DEP VARCHAR(20) NOT NULL,
	CI_DEP VARCHAR(9),
	SEXO_DEP VARCHAR(9) NOT NULL,
	EDAD_DEP NUMERIC(2,0) NOT NULL,
	PARENTESCO_DEP VARCHAR(7) NOT NULL
);

CREATE TABLE PRIMA (
	POSTIZA_PRIMA INT NOT NULL,
	MONTO_PRIMA REAL NOT NULL

);

CREATE TABLE PAGA (
	CI_EMP VARCHAR(9) NOT NULL,
	POSTIZA_PRIMA INT NOT NULL,
	POSTIZA_DEP INT NOT NULL
);

CREATE TABLE CARGO (
	POSTIZA_CARGO INT NOT NULL,
	NOMBRE_CARGO VARCHAR(13),
	SUELDO_BASE_CARGO REAL NOT NULL

);

CREATE TABLE ADMINISTRATIVO (
	CI_EMP VARCHAR(9) NOT NULL,
	POSTIZA_CARGO INT NOT NULL

);

CREATE TABLE CATEGORIA(
	POSTIZA_CATEGORIA INT NOT NULL,
	NOMBRE_CATEGORIA INT NOT NULL,
	SUELDO_BASE_CATEGORIA REAL NOT NULL
);

CREATE TABLE VENDEDORES (
	CI_EMP VARCHAR(9) NOT NULL,
	EXTRA_VENDEDOR INT NOT NULL,
	TURNO_VENDEDOR VARCHAR (10) NOT NULL,
	COMISION_VENDEDOR REAL NOT NULL
	POSTIZA_CATEGORIA INT NOT NULL
);

CREATE TABLE PRODUCTOS (
	POSTIZA_PROD INT NOT NULL,
	ANIO_PROD INT NOT NULL,
	MARCA_PROD VARCHAR(20) NOT NULL,
	MODELO_PROD VARCHAR(20) NOT NULL,
	PRECIO_PROD REAL NOT NULL,
	CANTIDAD_PROD INT NOT NULL,
	CATEGORIA_PROD VARCHAR(12)
);

CREATE TABLE VENDE (
	CI_EMP VARCHAR(9) NOT NULL,
	POSTIZA_PROD INT NOT NULL
);

CREATE TABLE INVENTARIO_N (
	NUMERO_INV_N NUMERIC(12,0) NOT NULL
);

CREATE TABLE NUEVO (
	POSTIZA_PROD INT NOT NULL,
	NUMERO_INV_N NUMERIC(12,0) NOT NULL,
	NIVEL_MINIMO BOOLEAN NOT NULL,
);

CREATE TABLE INVENTARIO_U (
	NUMERO_INV_U NUMERIC(12,0) NOT NULL,
);

CREATE TABLE USADO (
	POSTIZA_PROD INT NOT NULL,
	NUMERO_INV_U NUMERIC(12,0)
);

CREATE TABLE ORDEN (
	NRO_ORDEN NUMERIC(12,0) NOT NULL,
	FECHA TIMESTAMP NOT NULL,
	PROVEEDOR VARCHAR(20) NOT NULL,
	MONTO_ORDEN REAL NOT NULL,
	PRECIO_TOTAL REAL NOT NULL,
	PRECIO_UNITARIO REAL NOT NULL,
	CODIGO_ORDEN VARCHAR(12) NOT NULL,
	DESCRIPCION VARCHAR(200) NOT NULL,
	CANTIDAD_ORDEN INT NOT NULL
);

CREATE TABLE GENERA (
	POSTIZA_PROD INT NOT NULL,
	NRO_ORDEN NUMERIC(12,0) NOT NULL
);

CREATE TABLE PROVEEDORA (
	RIF VARCHAR(9) NOT NULL
);

CREATE TABLE FACTURA (
	NUMERO_FACTURA NUMERIC(12,0) NOT NULL,
	CANTIDAD_ENTREGADA INT NOT NULL
);

CREATE TABLE DESPACHA (
	NRO_ORDEN NUMERIC(12,0) NOT NULL,
	RIF VARCHAR(9) NOT NULL,
	NUMERO_FACTURA NUMERIC(12,0) NOT NULL
);

CREATE TABLE TRANSFERENCIA (
	NUMERO_TRANSACCION NUMERIC(12,0) NOT NULL,
	NUMERO_CUENTA NUMERIC(20,0) NOT NULL
);

CREATE TABLE CLIENTE (
	CI_CL VARCHAR(9) NOT NULL,
	NOMBRE_CL VARCHAR(9) NOT NULL,
	APELLIDO_CL VARCHAR(9) NOT NULL,
	CORREO_CL VARCHAR(40) NOT NULL,
	TELEFONO_CL NUMERIC(11,0) NOT NULL
	DIRECCION_CL VARCHAR(100) NOT NULL
);

CREATE TABLE OPERACIONES (
	POSTIZA_OPERACIONES INT NOT NULL
);

CREATE TABLE REALIZA (
	POSTIZA_OPERACIONES INT NOT NULL,
	CI_CL VARCHAR(9) NOT NULL
);

CREATE TABLE PAGOS (
	POSTIZA_PAGOS INT NOT NULL,
	TIPO_PAGOS VARCHAR(8) NOT NULL,
	CLAVE_CONFIRMACION NUMERIC(12,0),
	NRO_TARJETA NUMERIC(16,0)
);

CREATE TABLE SALDA (
	POSTIZA_OPERACIONES INT NOT NULL,
	POSTIZA_PAGOS INT NOT NULL
);

CREATE TABLE PEDIDOS (
	POSTIZA_OPERACIONES INT NOT NULL,
	ESTADO VARCHAR(19) NOT NULL
);

CREATE TABLE SOLICITA (
	POSTIZA_PROD INT NOT NULL,
	POSTIZA_OPERACIONES INT NOT NULL
);

CREATE TABLE COMPRA (
	POSTIZA_OPERACIONES INT NOT NULL,
	FACTURA_COMPRA VARCHAR(200) NOT NULL,
	MONTO_COMPRA INT NOT NULL
);

CREATE TABLE ADQUIERE (
	FACTURA_COMPRA VARCHAR(200) NOT NULL,
	POSTIZA_PROD INT NOT NULL,
	FECHA TIMESTAMP NOT NULL
);

CREATE TABLE TRUEQUE (
	POSTIZA_OPERACIONES INT NOT NULL,
	POSTIZA_PROD INT NOT NULL,
	RECIBO VARCHAR(100) NOT NULL,
	MONTO_TRUEQUE REAL NOT NULL
);

CREATE TABLE VENDER (
	POSTIZA_OPERACIONES INT NOT NULL,
	SALDO_VENDER REAL NOT NULL
);

CREATE TABLE CAMBIAR(
	POSTIZA_OPERACIONES INT NOT NULL,
	SALDO_CAMBIAR REAL NOT NULL
);