/* Proyecto 2

Bases de datos de VenTruePe Muebles

En este archivo se borran todas las tablas ya creadas.
Las restricciones vendran dadas en otro archivo.

Integrantes:
- Edgar Silva, carnet: 11-10968
- Douglas Torres, carnet: 11-11027
*/

DROP TABLE EMPLEADO
DROP TABLE TELEFONO_DE_EMPLEADO 
DROP TABLE DEPENDIENTES
DROP TABLE PRIMA
DROP TABLE PAGA
DROP TABLE CARGO
DROP TABLE ADMINISTRATIVO
DROP TABLE CATEGORIA
DROP TABLE VENDEDORES
DROP TABLE PRODUCTOS
DROP TABLE VENDE
DROP TABLE INVENTARIO_N
DROP TABLE NUEVO
DROP TABLE INVENTARIO_U
DROP TABLE USADO
DROP TABLE ORDEN
DROP TABLE GENERA
DROP TABLE PROVEEDORA
DROP TABLE FACTURA
DROP TABLE DESPACHA
DROP TABLE TRANSFERENCIA
DROP TABLE CLIENTE
DROP TABLE OPERACIONES
DROP TABLE REALIZA
DROP TABLE PAGOS
DROP TABLE SALDA
DROP TABLE PEDIDOS
DROP TABLE SOLICITA
DROP TABLE COMPRA
DROP TABLE ADQUIERE
DROP TABLE TRUEQUE
DROP TABLE VENDER
DROP TABLE CAMBIAR